/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.FlagStatus;
import modelo.ServicoProduto;
import modelo.Usuario;
import visao.util.FabricaVisoes;
import visao.util.GerenciadorServicoProduto;
import visao.util.GerenciadorUsuario;

/**
 *
 * @author florentino-ariza
 */
public class TelaListarServicosEProdutos extends javax.swing.JFrame {

    private ArrayList<ServicoProduto> servicosEProdutos;

    private boolean listarApenasDoUsuarioLogado;

    /**
     * Creates new form TelaListarServicosEProdutos
     */
    public TelaListarServicosEProdutos(boolean listarApenasDoUsuarioLogado) {
        initComponents();

        this.setLocationRelativeTo(null);

        this.listarApenasDoUsuarioLogado = listarApenasDoUsuarioLogado;

        preencherTable();
        criarPopupMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicosEProdutosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver serviços e produtos");

        jPanel.setBackground(new java.awt.Color(203, 210, 217));
        jPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 23, 22), 1, true));

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 23, 22));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Serviços e produtos");

        servicosEProdutosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(servicosEProdutosTable);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable servicosEProdutosTable;
    // End of variables declaration//GEN-END:variables

    private void preencherTable() {
        this.servicosEProdutos = GerenciadorServicoProduto.getProdutos();

        if (this.listarApenasDoUsuarioLogado) {
            String usuarioLogadoUuid = GerenciadorUsuario.getUsuarioLogado().getUuid();
            this.servicosEProdutos.removeIf(obj -> !obj.getUsuario().getUuid().equals(usuarioLogadoUuid));
        } else {
            this.servicosEProdutos.removeIf(obj -> obj.getFlagStatus() == FlagStatus.F);
        }

        Object nomes[] = servicosEProdutos.stream()
                .map(ServicoProduto::getNome)
                .collect(Collectors.toList())
                .toArray();

        Object precos[] = servicosEProdutos.stream()
                .map(ServicoProduto::getPreco)
                .collect(Collectors.toList())
                .toArray();

        Object categorias[] = servicosEProdutos.stream()
                .map(ServicoProduto::getCategoria)
                .collect(Collectors.toList())
                .toArray();

        Object servicoOuProduto[] = servicosEProdutos.stream()
                .map(ServicoProduto::getFlagSP)
                .collect(Collectors.toList())
                .toArray();

        Object vendaDoacaoOuTroca[] = servicosEProdutos.stream()
                .map(ServicoProduto::getFlagVDT)
                .collect(Collectors.toList())
                .toArray();

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("nome", nomes);
        tableModel.addColumn("preços", precos);
        tableModel.addColumn("categoria", categorias);
        tableModel.addColumn("S/P", servicoOuProduto);
        tableModel.addColumn("V/D/T", vendaDoacaoOuTroca);

        this.servicosEProdutosTable.setModel(tableModel);

    }

    private void criarPopupMenus() {
        JPopupMenu popupMenu = new JPopupMenu();

        if (this.listarApenasDoUsuarioLogado) {
            JMenuItem jMenuItemEditarSP = new JMenuItem("Editar");
            jMenuItemEditarSP.addActionListener((ActionEvent evt) -> {
                
                int linhaSelecionada = servicosEProdutosTable.getSelectedRow();
                ServicoProduto spSelecionado = servicosEProdutos.get(linhaSelecionada);
                FabricaVisoes.mostrarTelaEditarServicosEProdutos(spSelecionado);
            });

            JMenuItem jMenuItemExcluirSP = new JMenuItem("Excluir");
            jMenuItemExcluirSP.addActionListener((ActionEvent evt) -> {
                
                int linhaSelecionada = servicosEProdutosTable.getSelectedRow();
                ServicoProduto spSelecionado = servicosEProdutos.get(linhaSelecionada);
                GerenciadorServicoProduto.excluirServicoProduto(spSelecionado);

                preencherTable();
            });

            popupMenu.add(jMenuItemEditarSP);
            popupMenu.add(jMenuItemExcluirSP);

        } else {
            JMenuItem jMenuItemConversarComVendedor = new JMenuItem("Conversar com vendedor");
            jMenuItemConversarComVendedor.addActionListener((ActionEvent evt) -> {
                
                FabricaVisoes.esconderTela("TelaListarServicosEProdutos");

                int linhaSelecionada = servicosEProdutosTable.getSelectedRow();
                Usuario usuarioSelecionado = servicosEProdutos.get(linhaSelecionada).getUsuario();
                FabricaVisoes.mostrarTelaChat(usuarioSelecionado);
            });
            
            JMenuItem jMenuItemAbrirFecharStatus = new JMenuItem("Abrir/Fechar");
            jMenuItemAbrirFecharStatus.addActionListener((ActionEvent evt) -> {

                int linhaSelecionada = servicosEProdutosTable.getSelectedRow();
                ServicoProduto spSelecionado = servicosEProdutos.get(linhaSelecionada);
                GerenciadorServicoProduto.abrirFecharServicoProduto(spSelecionado);
                
                preencherTable();
            });

            popupMenu.add(jMenuItemConversarComVendedor);
        }

        servicosEProdutosTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                if (SwingUtilities.isRightMouseButton(evt)) 
                    return;
                
                int row = servicosEProdutosTable.rowAtPoint(evt.getPoint());
                int column = servicosEProdutosTable.columnAtPoint(evt.getPoint());

                if (!servicosEProdutosTable.isRowSelected(row)) {
                    servicosEProdutosTable.changeSelection(row, column, false, false);
                }
                
                popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        });
    }

}
