package visao;

import java.io.IOException;
import javax.swing.JOptionPane;
import org.json.JSONException;
import visao.util.FabricaVisoes;
import visao.util.GerenciadorUsuario;
import visao.util.TelaHomePageMenuButtons;

public class TelaHomePage extends javax.swing.JFrame {
    
    private TelaHomePageMenuButtons ultimoMenuBarSubmenuAberto;
    
    public TelaHomePage() {
        initComponents();

        this.setLocationRelativeTo(null);
        
        this.ultimoMenuBarSubmenuAberto = null;
        
        fecharTodosMenuBarSubmenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        minhaContaButton = new javax.swing.JButton();
        produtosEServicosButton = new javax.swing.JButton();
        chatButton = new javax.swing.JButton();
        chatMenu = new javax.swing.JPanel();
        broadcastButton = new javax.swing.JButton();
        minhaContaMenu = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        alterarDadosButton = new javax.swing.JButton();
        excluirContaButton = new javax.swing.JButton();
        produtosEServicosMenu = new javax.swing.JPanel();
        verTodosButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        verOfertadosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");

        jPanel1.setBackground(new java.awt.Color(203, 210, 217));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 23, 22), 1, true));
        jPanel1.setForeground(new java.awt.Color(203, 210, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(203, 210, 217));
        jSeparator1.setForeground(new java.awt.Color(203, 210, 217));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 54, 762, -1));

        minhaContaButton.setBackground(new java.awt.Color(203, 210, 217));
        minhaContaButton.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        minhaContaButton.setText("Minha conta");
        minhaContaButton.setToolTipText("");
        minhaContaButton.setBorder(null);
        minhaContaButton.setFocusable(false);
        minhaContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhaContaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(minhaContaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 13, 195, 35));

        produtosEServicosButton.setBackground(new java.awt.Color(203, 210, 217));
        produtosEServicosButton.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        produtosEServicosButton.setText("Produtos e serviços");
        produtosEServicosButton.setBorder(null);
        produtosEServicosButton.setFocusable(false);
        produtosEServicosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosEServicosButtonActionPerformed(evt);
            }
        });
        jPanel1.add(produtosEServicosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 13, -1, 35));

        chatButton.setBackground(new java.awt.Color(203, 210, 217));
        chatButton.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        chatButton.setText("Chat");
        chatButton.setToolTipText("");
        chatButton.setBorder(null);
        chatButton.setFocusable(false);
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });
        jPanel1.add(chatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 189, 35));

        chatMenu.setBackground(new java.awt.Color(238, 239, 243));
        chatMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        broadcastButton.setBackground(new java.awt.Color(238, 239, 243));
        broadcastButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        broadcastButton.setText("Broadcast");
        broadcastButton.setBorder(null);
        broadcastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broadcastButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chatMenuLayout = new javax.swing.GroupLayout(chatMenu);
        chatMenu.setLayout(chatMenuLayout);
        chatMenuLayout.setHorizontalGroup(
            chatMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(broadcastButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        chatMenuLayout.setVerticalGroup(
            chatMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatMenuLayout.createSequentialGroup()
                .addComponent(broadcastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jPanel1.add(chatMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 62, 160, -1));

        minhaContaMenu.setBackground(new java.awt.Color(238, 239, 243));
        minhaContaMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logoutButton.setBackground(new java.awt.Color(238, 239, 243));
        logoutButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        alterarDadosButton.setBackground(new java.awt.Color(238, 239, 243));
        alterarDadosButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        alterarDadosButton.setText("Alterar dados");
        alterarDadosButton.setBorder(null);
        alterarDadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosButtonActionPerformed(evt);
            }
        });

        excluirContaButton.setBackground(new java.awt.Color(238, 239, 243));
        excluirContaButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        excluirContaButton.setText("Excluir conta");
        excluirContaButton.setBorder(null);
        excluirContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirContaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout minhaContaMenuLayout = new javax.swing.GroupLayout(minhaContaMenu);
        minhaContaMenu.setLayout(minhaContaMenuLayout);
        minhaContaMenuLayout.setHorizontalGroup(
            minhaContaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(alterarDadosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(excluirContaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        minhaContaMenuLayout.setVerticalGroup(
            minhaContaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minhaContaMenuLayout.createSequentialGroup()
                .addComponent(alterarDadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.add(minhaContaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 62, -1, -1));

        produtosEServicosMenu.setBackground(new java.awt.Color(238, 239, 243));
        produtosEServicosMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        verTodosButton.setBackground(new java.awt.Color(238, 239, 243));
        verTodosButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        verTodosButton.setText("Ver todos");
        verTodosButton.setBorder(null);
        verTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodosButtonActionPerformed(evt);
            }
        });

        novoButton.setBackground(new java.awt.Color(238, 239, 243));
        novoButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        novoButton.setText("Novo");
        novoButton.setBorder(null);
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        verOfertadosButton.setBackground(new java.awt.Color(238, 239, 243));
        verOfertadosButton.setFont(new java.awt.Font("Ubuntu Thin", 0, 30)); // NOI18N
        verOfertadosButton.setText("Ver ofertados");
        verOfertadosButton.setBorder(null);
        verOfertadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOfertadosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout produtosEServicosMenuLayout = new javax.swing.GroupLayout(produtosEServicosMenu);
        produtosEServicosMenu.setLayout(produtosEServicosMenuLayout);
        produtosEServicosMenuLayout.setHorizontalGroup(
            produtosEServicosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verTodosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addComponent(novoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(verOfertadosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        produtosEServicosMenuLayout.setVerticalGroup(
            produtosEServicosMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtosEServicosMenuLayout.createSequentialGroup()
                .addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verOfertadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verTodosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.add(produtosEServicosMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 62, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minhaContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhaContaButtonActionPerformed
        this.abrirMenuBarSubmenus(TelaHomePageMenuButtons.MINHA_CONTA);
    }//GEN-LAST:event_minhaContaButtonActionPerformed

    private void produtosEServicosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosEServicosButtonActionPerformed
        this.abrirMenuBarSubmenus(TelaHomePageMenuButtons.PRODUTOS_E_SERVICOS);
    }//GEN-LAST:event_produtosEServicosButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
       this.abrirMenuBarSubmenus(TelaHomePageMenuButtons.CHAT);
    }//GEN-LAST:event_chatButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        FabricaVisoes.mostrarTelaNovoServicoProduto();
    }//GEN-LAST:event_novoButtonActionPerformed

    private void broadcastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broadcastButtonActionPerformed
        FabricaVisoes.mostrarTelaBroadcast();
    }//GEN-LAST:event_broadcastButtonActionPerformed

    private void alterarDadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosButtonActionPerformed
        FabricaVisoes.mostrarTelaAtualizacaoUsuario();
        FabricaVisoes.esconderTela("TelaHomePage");
    }//GEN-LAST:event_alterarDadosButtonActionPerformed

    private void verOfertadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOfertadosButtonActionPerformed
        FabricaVisoes.mostrarTelaListarServicosEProdutos(true);
    }//GEN-LAST:event_verOfertadosButtonActionPerformed

    private void verTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodosButtonActionPerformed
        FabricaVisoes.mostrarTelaListarServicosEProdutos(false);
    }//GEN-LAST:event_verTodosButtonActionPerformed

    private void excluirContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirContaButtonActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza?");
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                if (GerenciadorUsuario.excluirUsuario()) {
                    JOptionPane.showMessageDialog(null, "Conta excluída...");
                    GerenciadorUsuario.desconectar();
                    FabricaVisoes.mostrarTelaLogin();
                    FabricaVisoes.esconderTela("TelaHomePage");
                } else {
                    JOptionPane.showMessageDialog(null, "A conta não pôde ser excluída.");
                }
            } catch (JSONException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_excluirContaButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        GerenciadorUsuario.fazerLogoutUsuario();
        GerenciadorUsuario.desconectar();
        FabricaVisoes.mostrarTelaLogin();
        FabricaVisoes.esconderTela("TelaHomePage");
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarDadosButton;
    private javax.swing.JButton broadcastButton;
    private javax.swing.JButton chatButton;
    private javax.swing.JPanel chatMenu;
    private javax.swing.JButton excluirContaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton minhaContaButton;
    private javax.swing.JPanel minhaContaMenu;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton produtosEServicosButton;
    private javax.swing.JPanel produtosEServicosMenu;
    private javax.swing.JButton verOfertadosButton;
    private javax.swing.JButton verTodosButton;
    // End of variables declaration//GEN-END:variables

    private void fecharTodosMenuBarSubmenus() {
        produtosEServicosMenu.setVisible((false));
        chatMenu.setVisible(false);
        minhaContaMenu.setVisible(false);
    }

    private void abrirMenuBarSubmenus(TelaHomePageMenuButtons menuButton) {
       this.fecharTodosMenuBarSubmenus();
       
       if (this.ultimoMenuBarSubmenuAberto != null && this.ultimoMenuBarSubmenuAberto == menuButton) {
           this.ultimoMenuBarSubmenuAberto = null;
           return;
       }
        
       switch (menuButton) {
            case PRODUTOS_E_SERVICOS:
                this.produtosEServicosMenu.setVisible(true);
                break;
            case CHAT:
                this.chatMenu.setVisible(true);
                break;
            case MINHA_CONTA:
                this.minhaContaMenu.setVisible(true);
                break;
            default:
                break;
        }
       
       this.ultimoMenuBarSubmenuAberto = menuButton;
    }
}
