package visao;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONException;
import visao.util.FabricaVisoes;
import visao.util.GerenciadorServicoProduto;

public class TelaCadastroProduto extends javax.swing.JFrame {

    public TelaCadastroProduto() {
        initComponents();

        buttonGroupCategoria.add(jRadioButtonLazer);
        buttonGroupCategoria.add(jRadioButtonLimpeza);
        buttonGroupCategoria.add(jRadioButtonModa);

        jRadioButtonModa.setActionCommand(jRadioButtonModa.getText().toLowerCase());
        jRadioButtonLimpeza.setActionCommand(jRadioButtonLimpeza.getText().toLowerCase());
        jRadioButtonLazer.setActionCommand(jRadioButtonLazer.getText().toLowerCase());

        buttonGroupTipo.add(jRadioButtonServico);
        buttonGroupTipo.add(jRadioButtonProduto);

        jRadioButtonServico.setActionCommand("s");
        jRadioButtonProduto.setActionCommand("p");

        buttonGroupVDT.add(jRadioButtonVenda);
        buttonGroupVDT.add(jRadioButtonTroca);
        buttonGroupVDT.add(jRadioButtonDoacao);

        jRadioButtonVenda.setActionCommand("v");
        jRadioButtonDoacao.setActionCommand("d");
        jRadioButtonTroca.setActionCommand("t");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCategoria = new javax.swing.ButtonGroup();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupVDT = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonLazer = new javax.swing.JRadioButton();
        jRadioButtonLimpeza = new javax.swing.JRadioButton();
        jRadioButtonModa = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonServico = new javax.swing.JRadioButton();
        jRadioButtonProduto = new javax.swing.JRadioButton();
        jRadioButtonVenda = new javax.swing.JRadioButton();
        jRadioButtonDoacao = new javax.swing.JRadioButton();
        jRadioButtonTroca = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de produto ou serviço");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Título:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Categoria:");

        jRadioButtonLazer.setText("Lazer");

        jRadioButtonLimpeza.setText("Limpeza");

        jRadioButtonModa.setText("Moda");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tipo:");

        jRadioButtonServico.setText("Serviço");

        jRadioButtonProduto.setText("Produto");

        jRadioButtonVenda.setText("Venda");

        jRadioButtonDoacao.setText("Doação");

        jRadioButtonTroca.setText("Troca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRadioButtonLazer)
                                        .addGap(33, 33, 33)
                                        .addComponent(jRadioButtonLimpeza))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRadioButtonServico)
                                        .addGap(75, 75, 75)
                                        .addComponent(jRadioButtonProduto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonModa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jRadioButtonVenda)
                        .addGap(86, 86, 86)
                        .addComponent(jRadioButtonDoacao)
                        .addGap(63, 63, 63)
                        .addComponent(jRadioButtonTroca)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonVenda)
                    .addComponent(jRadioButtonDoacao)
                    .addComponent(jRadioButtonTroca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonLazer)
                    .addComponent(jRadioButtonLimpeza)
                    .addComponent(jRadioButtonModa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonServico)
                    .addComponent(jRadioButtonProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonVoltar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        FabricaVisoes.esconderTela("TelaCadastroProduto");
        FabricaVisoes.mostrarTelaHomePage();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String titulo = jTextFieldTitulo.getText().trim();
        String descricao = jTextArea1.getText().trim();
        float valor = Float.valueOf(jTextFieldValor.getText().trim());
        String categoria = buttonGroupCategoria.getSelection().getActionCommand();
        String flagSP = buttonGroupTipo.getSelection().getActionCommand();
        String flagVDT = buttonGroupVDT.getSelection().getActionCommand();
        try {
            if (GerenciadorServicoProduto.cadastrarProduto(titulo, descricao, categoria, valor, flagSP, flagVDT)) {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                FabricaVisoes.esconderTela("TelaCadastroProduto");
                FabricaVisoes.mostrarTelaHomePage();
            } else {
                JOptionPane.showMessageDialog(null, "Erro no cadastro!");
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro no cadastro!");
            // Logger.getLogger(TelaCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro no cadastro!");
            //Logger.getLogger(TelaCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCategoria;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.ButtonGroup buttonGroupVDT;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonDoacao;
    private javax.swing.JRadioButton jRadioButtonLazer;
    private javax.swing.JRadioButton jRadioButtonLimpeza;
    private javax.swing.JRadioButton jRadioButtonModa;
    private javax.swing.JRadioButton jRadioButtonProduto;
    private javax.swing.JRadioButton jRadioButtonServico;
    private javax.swing.JRadioButton jRadioButtonTroca;
    private javax.swing.JRadioButton jRadioButtonVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
